[mypy]
python_version = 3.12
warn_unused_configs = True
ignore_missing_imports = True
show_error_codes = True
plugins = mypy_django_plugin.main
strict_optional = True
follow_imports = silent

[mypy.plugins.django-stubs]
django_settings_module = nutribot.settings

[mypy-backend.*]
strict = True

[mypy-bot.*]
strict = True
