line-length = 100
indent-width = 4
target-version = "py311"
extend-exclude = [
  "backend/apps/migrations",
]
respect-gitignore = true

[lint]
select = [
  "E",
  "F",
  "I",
  "UP",
]
ignore = []
fixable = ["ALL"]

[lint.isort]
known-first-party = ["apps", "bot", "nutribot"]

[lint.per-file-ignores]
"backend/apps/**/migrations/*.py" = ["ALL"]

[format]
quote-style = "double"
indent-style = "space"
line-ending = "lf"
