# Generated by Django 5.2.7 on 2025-10-12 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monitoring", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="applicationlog",
            new_name="monitoring__created_e2c9fe_idx",
            old_name="monitoring_created_level_idx",
        ),
        migrations.RenameIndex(
            model_name="applicationlog",
            new_name="monitoring__logger__43b0aa_idx",
            old_name="monitoring_logger_level_idx",
        ),
        migrations.AddField(
            model_name="applicationlog",
            name="group",
            field=models.CharField(
                choices=[
                    ("application", "Приложение"),
                    ("administrative", "Администрирование"),
                ],
                db_index=True,
                default="application",
                max_length=32,
            ),
        ),
    ]