# Generated by Django 5.2.7 on 2025-10-13 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "monitoring",
            "0002_rename_monitoring_created_level_idx_monitoring__created_e2c9fe_idx_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="applicationlog",
            name="group",
            field=models.CharField(
                choices=[
                    ("application", "Приложение"),
                    ("administrative", "Администрирование"),
                    ("service", "Служебные процессы"),
                ],
                db_index=True,
                default="application",
                max_length=32,
            ),
        ),
    ]