# Generated by hand for stable bootstrap
from django.db import migrations, models
import django.db.models.deletion
from django.conf import settings

def _list_default():
    return []

class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('telegram_id', models.BigIntegerField(blank=True, null=True, unique=True)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('sex', models.CharField(choices=[('m', 'Male'), ('f', 'Female'), ('o', 'Other')], default='m', max_length=1)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('height_cm', models.PositiveSmallIntegerField(default=170)),
                ('weight_kg', models.DecimalField(decimal_places=1, default=70.0, max_digits=5)),
                ('body_fat_pct', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('activity_level', models.CharField(choices=[('sedentary', 'Sedentary'), ('light', 'Light'), ('moderate', 'Moderate'), ('active', 'Active'), ('athlete', 'Athlete')], default='moderate', max_length=16)),
                ('goal', models.CharField(choices=[('lose', 'Lose fat'), ('maintain', 'Maintain'), ('gain', 'Gain'), ('recomp', 'Recomp')], default='recomp', max_length=16)),
                ('allergies', models.JSONField(blank=True, default=_list_default)),
                ('exclusions', models.JSONField(blank=True, default=_list_default)),
                ('daily_budget', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
