# Generated by Django 5.2.6 on 2025-09-13 11:04

import apps.users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='allergies',
            field=models.JSONField(blank=True, default=apps.users.models._list_default),
        ),
        migrations.AlterField(
            model_name='profile',
            name='exclusions',
            field=models.JSONField(blank=True, default=apps.users.models._list_default),
        ),
        migrations.AlterField(
            model_name='profile',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
