# Generated by Django 5.2.6 on 2025-09-19 09:48

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_profile_allergies_alter_profile_exclusions_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="calocoin_balance",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Баланс внутренней валюты CaloCoin",
                max_digits=10,
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="calocoin_rate_rub",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Сколько рублей стоит один CaloCoin",
                max_digits=7,
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="telegram_stars_balance",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="profile",
            name="telegram_stars_rate_rub",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Сколько рублей стоит одна Telegram Star при пополнении",
                max_digits=7,
            ),
        ),
    ]