# Generated by Django 5.2.6 on 2025-09-21 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_profile_calocoin_balance_profile_calocoin_rate_rub_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="experience_level",
            field=models.CharField(
                choices=[
                    ("newbie", "Новичок"),
                    ("enthusiast", "Энтузиаст"),
                    ("pro", "Профи"),
                    ("legend", "Легенда"),
                ],
                default="newbie",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="middle_name",
            field=models.CharField(blank=True, max_length=150),
        ),
    ]