# Generated by Django 5.2.6 on 2025-09-24 09:52

import apps.users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_profile_experience_level_profile_middle_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="avatar_preferences",
            field=models.JSONField(
                blank=True, default=apps.users.models._avatar_preferences_default
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="wallet_settings",
            field=models.JSONField(
                blank=True, default=apps.users.models._wallet_settings_default
            ),
        ),
    ]