# Generated by Django 5.2.7 on 2025-10-06 18:41

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0006_paymentattempt_orders_payment_provider_external_unique"),
        ("users", "0005_profile_avatar_preferences_profile_wallet_settings"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="telegram_stars_balance",
            field=models.PositiveIntegerField(
                default=0,
                help_text="[deprecated] Используйте леджер TelegramStarLedgerEntry для актуального баланса",
            ),
        ),
        migrations.CreateModel(
            name="TelegramStarLedgerEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "direction",
                    models.CharField(
                        choices=[("credit", "Зачисление"), ("debit", "Списание")],
                        max_length=16,
                    ),
                ),
                ("amount", models.PositiveIntegerField()),
                (
                    "occurred_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("description", models.CharField(blank=True, max_length=255)),
                ("source", models.CharField(blank=True, max_length=64)),
                (
                    "telegram_payment_charge_id",
                    models.CharField(
                        blank=True,
                        help_text="Идентификатор successful_payment из Telegram",
                        max_length=128,
                        null=True,
                    ),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="star_ledger_entries",
                        to="users.profile",
                    ),
                ),
                (
                    "wallet_transaction",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="star_ledger_entry",
                        to="orders.wallettransaction",
                    ),
                ),
            ],
            options={
                "verbose_name": "Запись леджера Stars",
                "verbose_name_plural": "Леджер Stars",
                "indexes": [
                    models.Index(
                        fields=["profile", "direction"],
                        name="users_starledger_prof_dir",
                    ),
                    models.Index(fields=["occurred_at"], name="users_starledger_occur"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(
                            telegram_payment_charge_id__isnull=False
                        ),
                        fields=("telegram_payment_charge_id",),
                        name="users_starledger_unique_charge",
                    )
                ],
            },
        ),
    ]