# Generated by hand to backfill TelegramStarLedgerEntry from existing wallet transactions.
from __future__ import annotations

from django.db import migrations
from django.db.models import Case, F, IntegerField, Sum, Value, When


def forwards(apps, schema_editor):
    WalletTransaction = apps.get_model("orders", "WalletTransaction")
    LedgerEntry = apps.get_model("users", "TelegramStarLedgerEntry")
    Profile = apps.get_model("users", "Profile")

    currency = "STARS"
    credit = "credit"
    debit = "debit"
    confirmed = "confirmed"

    existing_entries = set(
        LedgerEntry.objects.values_list("wallet_transaction_id", flat=True)
    )

    to_update_profiles = set()

    transactions = (
        WalletTransaction.objects.filter(
            currency=currency,
            direction__in=[credit, debit],
            status=confirmed,
        )
        .select_related("profile")
        .order_by("occurred_at", "pk")
    )

    for tx in transactions.iterator():
        direction = credit if tx.direction == credit else debit
        defaults = {
            "profile_id": tx.profile_id,
            "direction": direction,
            "amount": int(tx.amount),
            "occurred_at": tx.occurred_at,
            "description": tx.description or "",
            "source": (tx.metadata or {}).get("source", "") if tx.metadata else "",
            "metadata": tx.metadata or {},
            "telegram_payment_charge_id": (tx.metadata or {}).get("telegram_payment_charge_id")
            if tx.metadata
            else None,
        }
        if tx.pk in existing_entries:
            entry = LedgerEntry.objects.get(wallet_transaction_id=tx.pk)
            updates = {}
            for key, value in defaults.items():
                if getattr(entry, key) != value:
                    updates[key] = value
            if updates:
                for key, value in updates.items():
                    setattr(entry, key, value)
                entry.save(update_fields=list(updates.keys()) + ["updated_at"])
        else:
            LedgerEntry.objects.create(wallet_transaction_id=tx.pk, **defaults)
        to_update_profiles.add(tx.profile_id)

    if to_update_profiles:
        aggregates = (
            LedgerEntry.objects.filter(profile_id__in=to_update_profiles)
            .values("profile_id")
            .annotate(
                balance=Sum(
                    Case(
                        When(direction=credit, then=F("amount")),
                        When(direction=debit, then=-F("amount")),
                        default=Value(0),
                        output_field=IntegerField(),
                    )
                )
            )
        )
        for item in aggregates:
            Profile.objects.filter(pk=item["profile_id"]).update(
                telegram_stars_balance=int(item["balance"] or 0)
            )


def backwards(apps, schema_editor):
    # No-op: ledger entries can remain when rolling back.
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0006_alter_profile_telegram_stars_balance_and_more"),
    ]

    operations = [
        migrations.RunPython(forwards, backwards, elidable=True),
    ]