# Generated by Django 5.2.7 on 2025-10-13 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_populate_star_ledger"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="stars_purchase_blocked",
            field=models.BooleanField(
                default=False,
                help_text="Если True — Telegram запрещает покупки Stars для этого пользователя",
            ),
        ),
    ]