# Generated by Django 5.2.7 on 2025-10-14 15:12

import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0008_add_stars_purchase_blocked"),
    ]

    operations = [
        migrations.CreateModel(
            name="StarsRevenueSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fetched_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("stars_total", models.PositiveIntegerField(default=0)),
                (
                    "revenue_rub",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                ("currency", models.CharField(default="RUB", max_length=8)),
                (
                    "rate_rub",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0.0000"), max_digits=10
                    ),
                ),
                ("payload", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "verbose_name": "Снимок метрик Stars",
                "verbose_name_plural": "Метрики Stars",
                "ordering": ("-fetched_at", "-id"),
            },
        ),
    ]