# Generated by Django 5.2.7 on 2025-10-17 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0009_starsrevenuesnapshot"),
    ]

    operations = [
        migrations.AlterField(
            model_name="telegramstarledgerentry",
            name="telegram_payment_charge_id",
            field=models.CharField(
                blank=True,
                help_text="Идентификатор successful_payment из Telegram",
                max_length=255,
                null=True,
            ),
        ),
    ]