# Generated by Django 5.2.8 on 2025-11-17 20:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0011_telegramintegrationlink"),
    ]

    operations = [
        migrations.CreateModel(
            name="TelegramSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("access_token", models.CharField(max_length=1024)),
                ("refresh_token", models.CharField(max_length=1024)),
                ("expires_at", models.DateTimeField()),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "profile",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="telegram_session",
                        to="users.profile",
                    ),
                ),
            ],
        ),
    ]
