# Generated by Django 5.2.1 on 2025-09-27 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_wallet_targets_perks_resilient"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RenameIndex(
                    model_name="walletperk",
                    new_name="orders_wall_profile_740eac_idx",
                    old_name="orders_wperk_profile_active_idx",
                ),
            ],
            database_operations=[
                migrations.RunSQL(
                    sql="ALTER INDEX IF EXISTS orders_wperk_profile_active_idx RENAME TO orders_wall_profile_740eac_idx;",
                    reverse_sql="ALTER INDEX IF EXISTS orders_wall_profile_740eac_idx RENAME TO orders_wperk_profile_active_idx;",
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RenameIndex(
                    model_name="wallettarget",
                    new_name="orders_wall_profile_a7537c_idx",
                    old_name="orders_wtarget_profile_curr_active_idx",
                ),
            ],
            database_operations=[
                migrations.RunSQL(
                    sql="ALTER INDEX IF EXISTS orders_wtarget_profile_curr_active_idx RENAME TO orders_wall_profile_a7537c_idx;",
                    reverse_sql="ALTER INDEX IF EXISTS orders_wall_profile_a7537c_idx RENAME TO orders_wtarget_profile_curr_active_idx;",
                ),
            ],
        ),
    ]