# Generated by Django 5.2.6 on 2025-09-27 11:40

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "orders",
            "0003_rename_orders_wperk_profile_active_idx_orders_wall_profile_740eac_idx_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="wallettransaction",
            name="idempotency_key",
            field=models.CharField(
                default=uuid.uuid4,
                help_text="Используется для защиты от двойного списания",
                max_length=128,
            ),
        ),
    ]