# Generated by Django 5.2.6 on 2025-09-27 12:14

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0004_alter_wallettransaction_idempotency_key"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="description",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="order",
            name="kind",
            field=models.CharField(
                choices=[
                    ("pro_subscription", "PRO подписка"),
                    ("consultation", "Консультация"),
                    ("digital_product", "Цифровой продукт"),
                    ("other", "Другое"),
                ],
                default="pro_subscription",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="payment_transaction",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="payment_order",
                to="orders.wallettransaction",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="reference",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="order",
            name="title",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="wallettransaction",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="wallettransaction",
            name="description",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="wallettransaction",
            name="reference",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name="order",
            name="address_line",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="order",
            name="city",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name="order",
            name="delivery_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="delivery_service",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="orders",
                to="orders.deliveryservice",
            ),
        ),
    ]