# Generated by Django 5.2.6 on 2025-09-28 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0005_order_description_order_kind_and_more"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="paymentattempt",
            constraint=models.UniqueConstraint(
                condition=models.Q(("external_payment_id__gt", "")),
                fields=("provider", "external_payment_id"),
                name="orders_payment_provider_external_unique",
            ),
        ),
    ]