# Generated by Django 5.2.7 on 2025-10-14 15:12

from django.db import migrations, models
from django.db.models import Q


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0008_wallettransaction_updated_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymentattempt",
            name="telegram_payment_charge_id",
            field=models.CharField(
                blank=True,
                help_text="Идентификатор платежа из Telegram successful_payment",
                max_length=128,
            ),
        ),
        migrations.AddIndex(
            model_name="paymentattempt",
            index=models.Index(
                fields=["telegram_payment_charge_id"], name="orders_payment_charge_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="paymentattempt",
            constraint=models.UniqueConstraint(
                condition=Q(telegram_payment_charge_id__gt=""),
                fields=("provider", "telegram_payment_charge_id"),
                name="orders_payment_provider_charge_unique",
            ),
        ),
    ]