# Generated by Django 5.2.7 on 2025-10-16 18:25

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0009_paymentattempt_telegram_payment_charge_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paymentattempt",
            name="telegram_payment_charge_id",
            field=models.CharField(
                blank=True,
                help_text="Идентификатор платежа из Telegram successful_payment",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="wallettransaction",
            name="idempotency_key",
            field=models.CharField(
                default=uuid.uuid4,
                help_text="Используется для защиты от двойного списания",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="wallettransaction",
            name="reference",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]