# Generated by Django 5.2.7 on 2025-10-17 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0010_alter_paymentattempt_telegram_payment_charge_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="integrationwebhookevent",
            name="external_event_id",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]