# Generated by Django 5.2.6 on 2025-09-24 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="menuitem",
            name="external_id",
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
    ]