# Generated by Django 5.2.6 on 2025-09-25 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_menuitem_external_id"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="menuitem",
            new_name="cat_menuitem_source_idx",
            old_name="catalog_men_source_de0e54_idx",
        ),
        migrations.AddIndex(
            model_name="menuitem",
            index=models.Index(
                fields=["is_available", "price"], name="cat_menuitem_avail_price_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="menuitem",
            index=models.Index(fields=["tags"], name="cat_menuitem_tags_idx"),
        ),
        migrations.AddIndex(
            model_name="menuitem",
            index=models.Index(fields=["allergens"], name="cat_menuitem_allergens_idx"),
        ),
        migrations.AddIndex(
            model_name="menuitem",
            index=models.Index(
                fields=["exclusions"], name="cat_menuitem_exclusions_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="restaurant",
            index=models.Index(
                fields=["city", "is_active"], name="cat_rest_city_active_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="store",
            index=models.Index(
                fields=["city", "is_active"], name="cat_store_city_active_idx"
            ),
        ),
    ]