# Generated by Django 5.2.8 on 2025-11-21 19:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_rename_catalog_men_source_de0e54_idx_cat_menuitem_source_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='nutrients',
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='item',
                to='catalog.nutrients',
            ),
        ),
    ]
