# Generated by Django 5.2.7 on 2025-11-01 09:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("market", "0003_market_metadata_indexes"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="cart",
            index=models.Index(
                fields=["user", "-updated_at"], name="market_cart_user_updated_desc"
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(fields=["price"], name="market_product_price"),
        ),
        migrations.AddIndex(
            model_name="recipe",
            index=models.Index(
                fields=["cooking_time_minutes"], name="market_recipe_cook_time"
            ),
        ),
        migrations.AddIndex(
            model_name="store",
            index=models.Index(fields=["city"], name="market_store_city"),
        ),
    ]
