# Generated by Django 5.2.8 on 2025-11-06 08:21

import django.core.validators
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("market", "0004_cart_market_cart_user_updated_desc_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="mealplan",
            name="price_amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
            ),
        ),
        migrations.AddField(
            model_name="mealplan",
            name="price_currency",
            field=models.CharField(default="RUB", max_length=3),
        ),
        migrations.AddIndex(
            model_name="mealplan",
            index=models.Index(
                fields=["is_published", "price_amount"], name="market_plan_price_pub"
            ),
        ),
    ]
