# Generated by Django 5.2.8 on 2025-11-08 11:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("market", "0005_mealplan_price_amount_mealplan_price_currency_and_more"),
        ("orders", "0011_alter_integrationwebhookevent_external_event_id"),
        ("users", "0010_alter_telegramstarledgerentry_telegram_payment_charge_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="MealPlanAccess",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("granted_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "meal_plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="premium_accesses",
                        to="market.mealplan",
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="market_meal_plan_accesses",
                        to="users.profile",
                    ),
                ),
                (
                    "wallet_transaction",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="meal_plan_accesses",
                        to="orders.wallettransaction",
                    ),
                ),
            ],
            options={
                "verbose_name": "Meal plan access",
                "verbose_name_plural": "Meal plan accesses",
                "indexes": [
                    models.Index(
                        fields=["profile", "meal_plan"],
                        name="market_planaccess_profile_plan",
                    ),
                    models.Index(
                        fields=["meal_plan", "granted_at"],
                        name="market_planaccess_plan_date",
                    ),
                ],
                "unique_together": {("profile", "meal_plan")},
            },
        ),
        migrations.CreateModel(
            name="RecipeAccess",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("granted_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="market_recipe_accesses",
                        to="users.profile",
                    ),
                ),
                (
                    "recipe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="premium_accesses",
                        to="market.recipe",
                    ),
                ),
                (
                    "wallet_transaction",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="recipe_accesses",
                        to="orders.wallettransaction",
                    ),
                ),
            ],
            options={
                "verbose_name": "Recipe access",
                "verbose_name_plural": "Recipe accesses",
                "indexes": [
                    models.Index(
                        fields=["profile", "recipe"],
                        name="market_recacc_profile_recipe",
                    ),
                    models.Index(
                        fields=["recipe", "granted_at"],
                        name="market_recacc_recipe_date",
                    ),
                ],
                "unique_together": {("profile", "recipe")},
            },
        ),
    ]
