# Generated by Django 5.2.6 on 2025-09-24 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nutrition", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="menuplan",
            name="status",
            field=models.CharField(
                choices=[
                    ("generated", "Сгенерирован"),
                    ("accepted", "Принят"),
                    ("rejected", "Отклонён"),
                    ("recalculated", "Пересчитан"),
                ],
                default="generated",
                max_length=16,
            ),
        ),
    ]