# Generated by Django 5.2.6 on 2025-09-28 13:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nutrition", "0003_menuplan_processing_and_meal_note"),
    ]

    operations = [
        migrations.CreateModel(
            name="MenuPlanSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("summary", models.JSONField(blank=True, default=dict)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "plan",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="snapshot",
                        to="nutrition.menuplan",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["updated_at"], name="nutriplan_snapshot_updated_idx"
                    )
                ],
            },
        ),
    ]