# Generated by Django 5.2.7 on 2025-10-17 17:32

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FeedTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=80)),
                ("slug", models.SlugField(max_length=80, unique=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("generic", "Generic"),
                            ("news", "News"),
                            ("recipe", "Recipe"),
                            ("deal", "Deal"),
                        ],
                        default="generic",
                        max_length=16,
                    ),
                ),
            ],
            options={
                "verbose_name": "Feed tag",
                "verbose_name_plural": "Feed tags",
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="DealOffer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("external_id", models.CharField(max_length=255, unique=True)),
                ("title", models.CharField(max_length=160)),
                ("product_name", models.CharField(max_length=160)),
                ("network", models.CharField(max_length=120)),
                ("city", models.CharField(max_length=120)),
                ("address", models.CharField(blank=True, max_length=255)),
                ("is_online", models.BooleanField(default=False)),
                ("price_before", models.DecimalField(decimal_places=2, max_digits=8)),
                ("price_after", models.DecimalField(decimal_places=2, max_digits=8)),
                (
                    "discount_percent",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                ("valid_until", models.DateTimeField()),
                ("offer_url", models.URLField(blank=True)),
                ("image_url", models.URLField(blank=True)),
                (
                    "tags",
                    models.ManyToManyField(
                        blank=True, related_name="deal_offers", to="feed.feedtag"
                    ),
                ),
            ],
            options={
                "verbose_name": "Deal offer",
                "verbose_name_plural": "Deal offers",
                "ordering": ("-valid_until", "-id"),
            },
        ),
        migrations.CreateModel(
            name="NewsArticle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("source_id", models.CharField(max_length=255, unique=True)),
                ("title", models.CharField(max_length=240)),
                ("lead", models.TextField()),
                ("source_name", models.CharField(max_length=120)),
                ("source_url", models.URLField()),
                (
                    "published_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("preview_image_url", models.URLField(blank=True)),
                (
                    "toxicity_score",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0"), max_digits=5
                    ),
                ),
                (
                    "clickbait_score",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0"), max_digits=5
                    ),
                ),
                ("is_flagged", models.BooleanField(default=False)),
                (
                    "tags",
                    models.ManyToManyField(
                        blank=True, related_name="news_articles", to="feed.feedtag"
                    ),
                ),
            ],
            options={
                "verbose_name": "News article",
                "verbose_name_plural": "News articles",
                "ordering": ("-published_at", "-id"),
            },
        ),
        migrations.CreateModel(
            name="Recipe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("moderation", "Moderation"),
                            ("published", "Published"),
                            ("hidden", "Hidden"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=180)),
                ("slug", models.SlugField(max_length=200, unique=True)),
                ("short_description", models.CharField(max_length=280)),
                ("description", models.TextField(blank=True)),
                ("hero_image", models.URLField(blank=True)),
                ("gallery", models.JSONField(blank=True, default=list)),
                ("cook_time_minutes", models.PositiveSmallIntegerField(default=15)),
                (
                    "difficulty",
                    models.CharField(
                        choices=[
                            ("easy", "Легко"),
                            ("medium", "Средне"),
                            ("hard", "Сложно"),
                        ],
                        default="easy",
                        max_length=16,
                    ),
                ),
                (
                    "calories",
                    models.DecimalField(
                        decimal_places=1,
                        max_digits=6,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                    ),
                ),
                (
                    "protein",
                    models.DecimalField(
                        decimal_places=1,
                        max_digits=6,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                    ),
                ),
                (
                    "fat",
                    models.DecimalField(
                        decimal_places=1,
                        max_digits=6,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                    ),
                ),
                (
                    "carbs",
                    models.DecimalField(
                        decimal_places=1,
                        max_digits=6,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                    ),
                ),
                ("allergens", models.JSONField(blank=True, default=list)),
                ("diet_tags", models.JSONField(blank=True, default=list)),
                ("base_content", models.TextField()),
                ("premium_content", models.TextField(blank=True)),
                ("is_premium", models.BooleanField(default=False)),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=8,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                    ),
                ),
                ("currency", models.CharField(default="RUB", max_length=3)),
                (
                    "rating",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=3
                    ),
                ),
                ("rating_count", models.PositiveIntegerField(default=0)),
                ("purchases_count", models.PositiveIntegerField(default=0)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recipes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tags",
                    models.ManyToManyField(
                        blank=True, related_name="recipes", to="feed.feedtag"
                    ),
                ),
            ],
            options={
                "verbose_name": "Recipe",
                "verbose_name_plural": "Recipes",
                "ordering": ("-created_at", "-id"),
            },
        ),
        migrations.CreateModel(
            name="RecipePurchase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=8,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                    ),
                ),
                ("currency", models.CharField(default="RUB", max_length=3)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Ожидает"),
                            ("completed", "Завершено"),
                            ("refunded", "Возврат"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("provider", models.CharField(default="test", max_length=64)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "recipe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="purchases",
                        to="feed.recipe",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recipe_purchases",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
                "unique_together": {("user", "recipe")},
            },
        ),
        migrations.CreateModel(
            name="RecipeReaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("like", "Лайк"),
                            ("save", "Сохранить"),
                            ("fire", "Огонь"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "recipe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reactions",
                        to="feed.recipe",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["recipe", "kind"], name="feed_reaction_recipe_kind"
                    )
                ],
                "unique_together": {("user", "recipe", "kind")},
            },
        ),
        migrations.CreateModel(
            name="RecipeStep",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("order", models.PositiveSmallIntegerField(default=1)),
                ("text", models.TextField()),
                ("media_url", models.URLField(blank=True)),
                (
                    "recipe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="steps",
                        to="feed.recipe",
                    ),
                ),
            ],
            options={
                "ordering": ("order", "id"),
                "unique_together": {("recipe", "order")},
            },
        ),
    ]