# Generated by Django 5.2.7 on 2025-10-23 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feed", "0002_newsarticle_tracking_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="newsarticle",
            name="body",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="newsarticle",
            name="body_orig",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="newsarticle",
            name="lang",
            field=models.CharField(blank=True, default="", max_length=10),
        ),
        migrations.AddField(
            model_name="newsarticle",
            name="lead_orig",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="newsarticle",
            name="title_orig",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="newsarticle",
            name="translated",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="newsarticle",
            name="translation_provider",
            field=models.CharField(blank=True, default="", max_length=32),
        ),
    ]