# Generated by Django 5.2.7 on 2025-10-25 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feed", "0003_newsarticle_body_newsarticle_body_orig_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="newsarticle",
            options={
                "ordering": ("-published_at", "-id"),
                "permissions": (
                    ("can_moderate_news", "Can moderate news articles"),
                    ("can_translate_news", "Can translate news articles"),
                ),
                "verbose_name": "News article",
                "verbose_name_plural": "News articles",
            },
        ),
        migrations.AddField(
            model_name="newsarticle",
            name="is_published",
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]